### ISSUE TITLE
Windows web client compliance

### ISSUE THREAD

**Issue by debrando** [prometeia/wsgidavpythodc#1]
> As a *customer*,
> I want to *access with Windows Explorer*
> so *I could use the remote folder as a local one*.

--- 
##### Acceptance Criteria 01: login
*Given* I'm on a windows machine
*When* I mount a network drive to my user area
*Then* I'm asked for PYTHO credentials and I could access with them.

##### Acceptance Criteria 02: file management
*Given* I have mounted the user area
*When* I try to play with files within it (copy, move, rename..)
*Then* it works as they are local.

##### Acceptance Criteria 03: file transfer
*Given* I have mounted the user area
*When* I try to copy and move files from/to the area and my local machine
*Then* it works as they are both local.

##### Acceptance Criteria 04: file transfer limit
*Given* I have mounted the user area
*When* I try to copy and move files from/to the area and my local machine
*Then* it fails *only* when the single file size is above the limit configured on registry.

---
### NOTES
- To properly login it could be necessary to change the value of *BasicAuthLevel* parameter to 2.
- The limit referred to in AC04 is the parameter *FileSizeLimitInBytes*.
- To mount a the user area on Windows use the command, `NET USE * <webdavuri>/<pythousername>/media <pythopassword> /USER:<pythousername>` e.g. `NET USE * http://127.0.0.1:8008/brandolinid/media XXyyZZpwd /USER:brandolinid`

![webdav-client-regedit.jpg](https://zube.io/files/prometeia/dc63730153a65e7d70630c3937116000-webdav-client-regedit.jpg)

**Comment by debrando** [comment]
Reimplementato con nuovo server, sembra andare: @loredanaribatto a te la parola!

**Comment by glaucouri** [comment]
Il protocollo dell'url, segue quello web  https o http?

**Comment by debrando** [comment]
@glaucouri sì tutto è mediato da NGINX, che tra l'altro per sicurezza comunque antepone una sua autenticazione a scanso di bug/attacchi al servizio wsgidav.

Questo significa che configurando l'endpoint in client che non pensano di parlare ad un webserver (es. WinSCP) e dunque chiedono server:porta e non il protocollo, va indicata la porta standard in funzione di come esposto il servizio

Esempio:
- host: pythodev.prometeia.it
- port: 443
- remote folder: /ufsa/brandolinid/media

**Comment by loredanaribatto** [comment]
i file caricati in ufsa (anche se li copio in altre cartelle richiedono l'autenticazione, ma mi propone quella disistema con il dominio della mia macchina quindi non posso mettere le credenziali dell'utente pythoalfa...è normale? ![image.png](https://zube.io/files/prometeia/0550fef3b30211da7f6ad0d0d12b7c0c-image.png)

Per il resto funziona tutto, mi pare!

**Comment by loredanaribatto** [comment]
pe rl'utlimo punto, ossia il caricamento delle risorse oltre limite di grandezza invece mi rimane bloccato, senza fallire. Magari lo riprovo dopo comunque.

**Comment by debrando** [comment]
Come discusso in chat, mi sa che ti imbatti nelle limitazioni del vecchio webdav client di WIndows7.

Riguardo all'editing, è comunque sconsigliato (soprattutto trattando file Office) effettuare l'editing remoto. Anche fare la *move* è sconsigliata, sempre meglio copiare e solo su succeso cancellare l'originale: casi in cui il client windows è convinto di aver copiato tutto ma è salito solo la metà dello stesso ne ho già individuati.

**Comment by loredanaribatto** [comment]
inserisco le limitazioni in doc
